name: Build and Push Docker Image
 
on:

  pull_request:

    branches:

      - main

  push:

    branches:

      - main

    tags:

      - v*
 
jobs:

  build:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    env:

      ENVIRONMENT: ""

      LOWERCASE_REPO: ""

    steps:

      - uses: actions/checkout@v3

        with:

          fetch-depth: 0

      - name: Get name for ECR repo #(used in image name)

        run: echo "LOWERCASE_REPO=$(echo ${{ github.event.repository.name }} | tr [A-Z] [a-z])" >> $GITHUB_ENV
 
      - name: Set Branch Environment

        if: github.ref_type != 'tag'

        run: |

          if [[ ${{ github.event.ref }} =~ ^refs/heads/develop$ ]]; then 

           echo "ENVIRONMENT=develop" >> $GITHUB_ENV;

          elif [[ ${{ github.event.ref }} =~ ^refs/heads/main$ ]]; then 

           echo "ENVIRONMENT=main" >> $GITHUB_ENV; 

          else

           exit 1;

          fi

      - name: Generate Docker Metadata

        id: meta

        uses: docker/metadata-action@v5

        env:

          DOCKER_METADATA_PR_HEAD_SHA: true

        with:

          # list of Docker images to use as base name for tags

          images: |

            ${{ secrets.LIGHT_DOCKER_REPOSITORY_URL }}/${{ env.LOWERCASE_REPO }}

          # generate Docker tags based on the following events/attributes

          tags: |

            type=sha,prefix=sha-

            type=sha,prefix=sha-,format=short

            type=sha,prefix=${{ env.ENVIRONMENT }}-sha-,format=short

            type=ref,event=pr

            type=ref,event=branch

            type=ref,event=tag
 
      - name: Login to LIGHT AWS ECR

        uses: docker/login-action@v3

        with:

          username: ${{ secrets.LIGHT_DOCKER_USER }}

          password: ${{ secrets.LIGHT_DOCKER_TOKEN }}

          registry: ${{ secrets.LIGHT_DOCKER_REPOSITORY_URL }}

          ecr: false # TODO: fix as this is misleading, set to false to enable use of LIGHT_DOCKER_TOKEN to auth with registry
 
      - name: Build and push docker images

        uses: docker/build-push-action@v4

        with:

          tags: ${{ steps.meta.outputs.tags }}

          push: true

          provenance: false
 